image: python:slim

stages:
  - deploy

before_script:
   - pip install twine
   - python -m pip install --upgrade pip setuptools wheel
   - python setup.py sdist bdist_wheel

deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  script:
    - twine upload dist/*
  only:
    - tags